const REWATCH_LINKS = [
    {
      type: 'link',
      label: 'video1',
      href: '#',
    },
    {
      type: 'link',
      label: 'video2',
      href: '#',
    },
  ];
  
  const EXTERNAL_LINKS = [
    {
      type: 'link',
      label: 'video3',
      href: 'google.com',
    },
  ]
  
  module.exports = {
    docsidebar: [
      // Create the autogenerated sidebar items based on the docs and folder structure
      // in the docs directory.
      {type: 'autogenerated', dirName: '.'},
      {
        type: 'category',
        label: 'ReWatch Video',
        link: {
          type: 'generated-index',
          title: 'Rewatch videos',
          description: "npm rewatch videos",
        },
        items: REWATCH_LINKS,
      },
      {
        type: 'category',
        label: 'All Dashboards',
        link: {
          type: 'generated-index',
          title: 'SLO dashboards',
          description: "datadog links",
        },
        items: EXTERNAL_LINKS,
      },
    ],
  };