const REWATCH_LINKS = [
    {
      type: 'link',
      label: 'How to Deploy ',
      href: '#',
    },
    {
      type: 'link',
      label: 'How to Build',
      href: '#',
    },
  ];
  
  const EXTERNAL_LINKS = [
    {
      type: 'link',
      label: 'How to Test',
      href: '/caches',
    },
  ]
  
  module.exports = {
    docsidebar: [
      // Create the autogenerated sidebar items based on the docs and folder structure
      // in the docs directory.
      {type: 'autogenerated', dirName: '.'},
      
      // {type: 'autogenerated', dirName: 'topics'},
      // {
      //   type: 'category',
      //   label: 'Guides',
      //   collapsible: true,
      //   collapsed: false,
      //   items: [
      //     'creating-pages',
      //     {
      //       type: 'category',
      //       label: 'Docs',
      //       items: ['introduction', 'sidebar', 'markdown-features', 'versioning'],
      //     },
      //   ],
      // }
      // {
      //   type: 'category',
      //   label: 'Training Videos',
      //   link: {
      //     type: 'generated-index',
      //     title: 'Training videos ',
      //     description: "trainings videos",
      //   },
      //   items: REWATCH_LINKS,
      // },
      // {
      //   type: 'category',
      //   label: 'System Design',
      //   link: {
      //     type: 'generated-index',
      //     title: 'System Design',
      //     description: "system design questions",
      //   },
      //   items: EXTERNAL_LINKS,
      // },
    ],
  };
