const REWATCH_LINKS = [
    {
      type: 'link',
      label: 'How to Deploy ',
      href: '#',
    },
    {
      type: 'link',
      label: 'How to Build',
      href: '#',
    },
  ];
  
  const EXTERNAL_LINKS = [
    {
      type: 'link',
      label: 'How to Test',
      href: 'github.com/ashishonce',
    },
  ]
  
  module.exports = {
    docsidebar: [
      // Create the autogenerated sidebar items based on the docs and folder structure
      // in the docs directory.
      {type: 'autogenerated', dirName: '.'},
      {
        type: 'category',
        label: 'Training Videos',
        link: {
          type: 'generated-index',
          title: 'Training videos ',
          description: "trainings videos",
        },
        items: REWATCH_LINKS,
      },
      {
        type: 'category',
        label: 'System Design',
        link: {
          type: 'generated-index',
          title: 'System Design',
          description: "system design questions",
        },
        items: EXTERNAL_LINKS,
      },
    ],
  };
