#!/bin/bash

# git submodule update --init
# git submodule foreach git pull origin main

# Remove current docs except for the category.json file
# rm -r docs/aml-templates


# Copy submodule documents
# mkdir docs/aml-templates

# cp -rp submodules/aml-templates/docs/* docs/aml-templates
# cp -rp submodules/aml-templates/*.md docs/aml-templates


# Move _category_.json files to doc root folders
# cp static/category/aml-templates_category.json docs/aml-templates/_category_.json
# cp static/category/meuse_category_.json docs/meuse/_category_.json

# Copy imagery to static folder
#mkdir -p static/docs/images
#cp -rp /img/. static/docs/images

# Remove files we want to exclude
# while read p; do
#   rm $p
# done < EXCLUDE
