#!/bin/bash

git submodule update --init
git submodule foreach git pull origin main

# verify that we have any changes to submodules before committing them.
if [[ `git status ./submodules --porcelain` ]]; then
  git add submodules/*
  git commit -m "Update submodules"
fi